### ISSUE TITLE
The Platform Status site is down

### ISSUE THREAD

**Issue by jameswomack** [mozilla/platform-status#501]
[See here](https://platform-status.mozilla.org/#shadow-dom)

Would [monitoring that site](https://status.mozilla.org/) help identify issues earlier?

![image](https://user-images.githubusercontent.com/77849/33522454-3e8cc9c6-d7a2-11e7-8a40-a41496f55997.png)

**Comment by marco-c** [comment]
Thanks for noticing this. We should have monitoring, but unfortunately this project currently doesn't have a maintainer (I'm taking care of it from time to time in my spare time).

The issue is coming from https://raw.githubusercontent.com/MicrosoftEdge/Status/production/status.json, which is invalid JSON (it contains a trailing comma).

**Comment by jameswomack** [comment]
@marco-c thanks!
