### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#8]
To be decided: Testing framework. @TimAbraldes @brendandahl @mykmelez  ?

**Comment by digitarald** [comment]
We can continue with mocha, like oghliner, and I would throw in [chai/bdd](http://chaijs.com/api/bdd/) as style.

**Comment by mykmelez** [comment]
@brendandahl uses chai/bdd (via its *expect* variant) in [oghliner/test/testBootstrap.js](https://github.com/mozilla/oghliner/blob/master/test/testBootstrap.js), and I'm using it oghliner/test/testConfigure.js, which I'm implementing in https://github.com/mozilla/oghliner/pull/60, so I recommend that style.

**Comment by TimAbraldes** [comment]
[The Intern](https://theintern.github.io/intern/#what-is-intern) claims to be the only test framework built on standards and includes a BDD interface. Seems like all test frameworks provide similar functionality, though, so we should probably go with whatever we collectively have the most experience with.

I don't have a preference for testing style, but momentum seems to be swinging toward BDD :)

**Comment by digitarald** [comment]
chai/bdd it is. @TimAbraldes can you add some scaffolding to kick unit tests off?

**Comment by TimAbraldes** [comment]
> chai/bdd it is

In the interest of being explicit, I believe we also decided on Mocha as the test framework

> @TimAbraldes can you add some scaffolding to kick unit tests off?

Will do!

**Comment by darkwing** [comment]
I used Intern for MDN's functional selenium testing:

https://github.com/mozilla/kuma/tree/master/tests/ui

I found it good, FWIW.

**Comment by TimAbraldes** [comment]
Since I've done a bunch of research into this, it's probably worthwhile to document what I think I've found so far.

My understanding thus far is that we want:
- Unit testing, which means the ability to write tests that directly execute pieces of our Node.js modules and verify the results
- End to end testing, which means the ability to write tests that simulate user interactions with the finished product (i.e. build output) and verify that those interactions go as expected
- To write all of our tests in BDD style

My reading has led me to believe that the only option for testing user interactions with the site is Selenium. The way to use Selenium is to

1. Download the Selenium server JAR file
1. Download any browser-specific drivers (e.g. Marionette for Firefox versions beyond release)
1. Run the Selenium server with a JVM
1. Connect to the server with a WebDriver client
1. Use the WebDriver client API to drive the browser through tests, asserting/expecting/failing as necessary

I feel like we can use gulp or our testing framework to check for the JAR file and start the server. Once the server is up and running we will start our test framework.

If we use Mocha, we would use [Selenium WebDriverJS](https://code.google.com/p/selenium/wiki/WebDriverJs) to configure our running Selenium instance and to actually drive the browser. This boils down to `require('selenium-webdriver')` and then calling various methods of the returned object during the test.

If we use Intern, the configuration is handled in a config file that Intern reads. Once a test is running, Intern exposes the WebDriver through `this.remote`. This appears to be identical to the object that we would get from `require('selenium-webdriver')` in mocha tests. One interesting note is that Intern facilitates an abstraction called [Page Objects](https://theintern.github.io/intern/#page-objects) so that tests are written against the Page Objects instead of using the WebDriver directly.

I'm working on Proof of Concept PRs that start the Selenium server and execute tests against it using either Mocha or Intern.

**Comment by marco-c** [comment]
> If we use Mocha, we would use Selenium WebDriverJS to configure our running Selenium instance and to actually drive the browser. This boils down to require('selenium-webdriver') and then calling various methods of the returned object during the test.

Note that this configuration doesn't support Firefox Nightly (or other non-release versions) yet. To use it with Firefox Nightly, we need to use Marionette (https://github.com/jgraham/wires/issues/24).

I suspect that Intern doesn't support non-release Firefox as well, if it's using the standard FirefoxDriver (Marionette is meant to replace it).

**Comment by marco-c** [comment]
P.S.: If there are no breaking changes between Firefox versions, the standard FirefoxDriver could work also on non-release versions, but it isn't explicitly supported.

**Comment by TimAbraldes** [comment]
> > If we use Mocha, we would use Selenium WebDriverJS to configure our running Selenium instance and to actually drive the browser. This boils down to require('selenium-webdriver') and then calling various methods of the returned object during the test.

> Note that this configuration doesn't support Firefox Nightly (or other non-release versions) yet. To use it with Firefox Nightly, we need to use Marionette (jgraham/wires#24).
> 
> I suspect that Intern doesn't support non-release Firefox as well, if it's using the standard FirefoxDriver (Marionette is meant to replace it).

Right! No matter what approach we take, we have to configure each browser driver somewhat independently, and to support Firefox versions newer than release, we have to use Marionette.

**Comment by marco-c** [comment]
Hopefully https://github.com/jgraham/wires/issues/24 will be fixed soon. It'd be really useful for our work since we're working with bleeding edge APIs.

**Comment by digitarald** [comment]
@TimAbraldes anything missing here or can we close it?

**Comment by TimAbraldes** [comment]
> @TimAbraldes anything missing here or can we close it?

We technically have a unit test, but it doesn't `require` any of our code modules so it doesn't really move us along in terms of code coverage.

I've been working on an initial unit test that pulls in an engine module but have been wrestling with getting the right combination of loader plugin and babel incantation to be able to load our ES2015 modules from the unit test. Once that's set up, it should be pretty clear how to build additional unit tests

**Comment by digitarald** [comment]
So we have the basics. v2 as this doesn't block release for now. We need it to make contributions easier in the future though.

**Comment by marco-c** [comment]
We have a few more tests now.
